import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [citation, setCitation] = useState("");

  const fetchCitation = async () => {
    const res = await fetch("/api/hello");
    const data = await res.json();
    setCitation(data);
  };

  return (
    <>
      <Head>
        <title>Ping API</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1>Ping API</h1>
        {citation && <p>"{citation.citation.citation}"</p>}
        {citation && (
          <p>
            <strong>{citation.citation.infos.personnage}</strong>
          </p>
        )}
        {citation && (
          <p>
            <strong>
              <i>
                {citation.citation.infos.saison} - {citation.citation.infos.episode}
              </i>
            </strong>
          </p>
        )}
        <button onClick={fetchCitation}>Généré une citation</button>
      </main>
    </>
  );
}
